"""Forward-evidence purity: classification, verification, quarantine.

The cost-observation tape must contain only evidence generated by the FROZEN
runner during the untouched forward period. This module enforces that:

- Every NEW observation carries full provenance (evidenceClass, freezeId,
  frozenGitCommit, codeFingerprint, runId, signalAt / simulatedExecutionAt /
  recordedAt timestamps, source).
- Legacy rows written before the schema existed are CLASSIFIED, never
  silently trusted: quarantine preserves every original byte while the
  calibration layer reads only verified rows.
- Temporal impossibilities (execution before signal, future timestamps,
  unparseable fields) are rejected outright.
- Tests write to temporary fixture paths only; the committed tape stays
  byte-identical across test runs (enforced by a suite test).

Evidence classes:
  forward-paper   produced by the frozen runner, matching the active freeze
  historical-sim  produced before the freeze (or under an older study)
  replay          exact duplicate of another observation
  fixture         synthetic symbol from unit-test fixtures
  test            non-universe symbol outside any fixture signature
  invalid         structurally broken (missing fields / bad numbers / dates)

Exclusion counters mirror the audit vocabulary: wrong_freeze, fixture_test,
bad_timestamps, invalid_numeric, missing_data, replay.
"""
from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

EVIDENCE_FORWARD_PAPER = "forward-paper"
EVIDENCE_HISTORICAL_SIM = "historical-sim"
EVIDENCE_REPLAY = "replay"
EVIDENCE_FIXTURE = "fixture"
EVIDENCE_TEST = "test"
EVIDENCE_INVALID = "invalid"

EXCL_WRONG_FREEZE = "wrong_freeze"
EXCL_FIXTURE_TEST = "fixture_test"
EXCL_BAD_TIMESTAMPS = "bad_timestamps"
EXCL_INVALID_NUMERIC = "invalid_numeric"
EXCL_MISSING_DATA = "missing_data"
EXCL_REPLAY = "replay"

_MAX_CLOCK_SKEW_SECONDS = 300.0


def _parse_iso(value) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
        return dt if dt.tzinfo else None
    except ValueError:
        return None


def temporal_problems(row: dict, now: datetime | None = None) -> list[str]:
    """Reject impossible temporal records. Returns problem strings."""
    now = now or datetime.now(UTC)
    problems = []
    ts = _parse_iso(row.get("ts"))
    if ts is None:
        problems.append("unparseable ts")
    elif (now - ts).total_seconds() < -_MAX_CLOCK_SKEW_SECONDS:
        problems.append("ts in the future beyond clock skew")
    signal = _parse_iso(row.get("signal_ts"))
    if signal is not None and ts is not None and signal > ts:
        problems.append("signal after execution")
    if row.get("signal_ts") is not None and signal is None:
        problems.append("unparseable signal_ts")
    return problems


def numeric_problems(row: dict) -> list[str]:
    problems = []
    for field in ("turnover", "predicted_cost_bps", "decision_close"):
        v = row.get(field)
        if v is None:
            continue
        try:
            fv = float(v)
        except (TypeError, ValueError):
            problems.append(f"non-numeric {field}")
            continue
        if field == "turnover":
            if fv < 0 or fv != fv:  # negative or NaN
                problems.append(f"invalid {field}")
        elif fv <= 0 or fv != fv or fv in (float("inf"),):
            problems.append(f"invalid {field}")
    return problems


def missing_problems(row: dict) -> list[str]:
    required = ("ts", "symbol", "side", "decision_close", "exec_price", "turnover")
    missing = []
    for f in required:
        v = row.get(f)
        if v is None or v == "":
            missing.append(f)
    if row.get("side") not in ("BUY", "SELL", "FLAT"):
        missing.append("side")
    return missing


# ---------------------------------------------------------------------------
# classification
# ---------------------------------------------------------------------------

def classify_legacy_row(
    row: dict,
    *,
    freeze_universe: set[str],
    freeze_id: str,
    frozen_at_iso: str,
    frozen_git_commit: str,
    seen_identity_hashes: set[str],
    now: datetime | None = None,
) -> tuple[str, str, dict]:
    """Return (evidenceClass, exclusionReason|None, enriched_row_copy).

    Precedence: invalid_numeric > bad_timestamps > missing_data >
    replay > wrong_freeze/fixture_test > forward-paper.
    Enriched copies carry provenance fields so NOTHING is lost in quarantine.
    """
    out = dict(row)
    out.setdefault("evidenceClass", None)

    # --- structural ---------------------------------------------------------
    miss = missing_problems(row)
    if miss:
        out["evidenceClass"] = EVIDENCE_INVALID
        return EVIDENCE_INVALID, EXCL_MISSING_DATA, {**out, "exclusionDetail": f"missing:{','.join(miss)}"}

    num = numeric_problems(row)
    if num:
        out["evidenceClass"] = EVIDENCE_INVALID
        return EVIDENCE_INVALID, EXCL_INVALID_NUMERIC, {**out, "exclusionDetail": ",".join(num)}

    # --- freeze membership (checked BEFORE temporal so synthetic symbols
    #     classify as fixture/test even when their fake timestamps are wild) --
    symbol = str(row.get("symbol"))
    ts = _parse_iso(row.get("ts"))
    frozen_dt = _parse_iso(frozen_at_iso)

    if symbol not in freeze_universe:
        out["evidenceClass"] = EVIDENCE_FIXTURE
        return EVIDENCE_FIXTURE, EXCL_FIXTURE_TEST, {
            **out,
            "exclusionDetail": f"symbol {symbol!r} not in freeze universe",
        }
    if frozen_dt is not None and ts is not None and ts < frozen_dt:
        out["evidenceClass"] = EVIDENCE_HISTORICAL_SIM
        return EVIDENCE_HISTORICAL_SIM, EXCL_WRONG_FREEZE, {
            **out,
            "exclusionDetail": "predates freeze",
            "freezeId": freeze_id,
            "frozenGitCommit": frozen_git_commit,
        }


    # --- temporal -----------------------------------------------------------
    temp = temporal_problems(row, now)
    if temp:
        out['evidenceClass'] = EVIDENCE_INVALID
        return EVIDENCE_INVALID, EXCL_BAD_TIMESTAMPS, {**out, 'exclusionDetail': ';'.join(temp)}

    # --- replay -------------------------------------------------------------
    identity = json.dumps(
        {k: row.get(k) for k in ("ts", "symbol", "side", "turnover",
                                 "decision_close", "exec_price")},
        sort_keys=True,
    )
    if identity in seen_identity_hashes:
        out["evidenceClass"] = EVIDENCE_REPLAY
        return EVIDENCE_REPLAY, EXCL_REPLAY, out
    seen_identity_hashes.add(identity)

    # --- verified forward paper --------------------------------------------
    out["evidenceClass"] = EVIDENCE_FORWARD_PAPER
    out["freezeId"] = freeze_id
    out["frozenGitCommit"] = frozen_git_commit
    out["provenance"] = "migrated-legacy"  # pre-schema rows cannot prove code fingerprint
    return EVIDENCE_FORWARD_PAPER, "", out


def quarantine_archive(
    src_path: str | Path,
    *,
    archive_path: str | Path,
    quarantine_path: str | Path,
    keep_path: str | Path,
    freeze_manifest: dict,
    now: datetime | None = None,
) -> dict:
    """Migrate a legacy mixed tape WITHOUT losing a byte.

    - archive_path receives the original file, byte-identical.
    - quarantine_path receives EVERY row, annotated with its class/reason.
    - keep_path receives ONLY verified forward-paper rows, upgraded to the
      enriched schema, so the production tape starts pure.
    """
    src = Path(src_path)
    raw = src.read_bytes()
    Path(archive_path).parent.mkdir(parents=True, exist_ok=True)
    Path(archive_path).write_bytes(raw)

    config = freeze_manifest["config"]
    universe = {a["symbol"] for a in config["assets"]}
    freeze_id = f"freeze/{freeze_manifest['frozen_at_date']}"
    commit = freeze_manifest.get("git_commit_at_freeze") or ""

    entries = [json.loads(line) for line in raw.decode("utf-8").splitlines() if line.strip()]
    seen: set[str] = set()
    kept: list[dict] = []
    excluded: dict[str, int] = {}
    quarantined: list[dict] = []

    for row in entries:
        cls, reason, enriched = classify_legacy_row(
            row,
            freeze_universe=universe,
            freeze_id=freeze_id,
            frozen_at_iso=freeze_manifest["frozen_at"],
            frozen_git_commit=commit,
            seen_identity_hashes=seen,
            now=now,
        )
        enriched["evidenceClass"] = cls
        if reason:
            enriched["exclusionReason"] = reason
            excluded[reason] = excluded.get(reason, 0) + 1
            quarantined.append(enriched)
        else:
            kept.append(enriched)
            quarantined.append(enriched)  # everything appears in the audit copy

    def _dump(path: str | Path, rows: list[dict]) -> None:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            for r in rows:
                f.write(json.dumps(r, sort_keys=True) + "\n")

    _dump(quarantine_path, quarantined)
    _dump(keep_path, kept)

    return {
        "rows_total": len(entries),
        "kept_forward_paper": len(kept),
        "excluded": excluded,
        "archive_path": str(archive_path),
        "quarantine_path": str(quarantine_path),
        "keep_path": str(keep_path),
    }


# ---------------------------------------------------------------------------
# verification gate used by calibration
# ---------------------------------------------------------------------------

def verified_forward_rows(rows: list[dict], freeze_manifest: dict, now: datetime | None = None) -> tuple[list[dict], dict[str, int]]:
    """Filter a mixed row list down to VERIFIED forward-paper observations.

    Verified means: evidenceClass == forward-paper AND freezeId/frozenGitCommit
    match the active freeze AND temporally possible AND numerically sane.
    Returns (verified_rows, exclusion_counts).
    """
    expected_commit = freeze_manifest.get("git_commit_at_freeze") or ""
    freeze_id = f"freeze/{freeze_manifest['frozen_at_date']}"
    now = now or datetime.now(UTC)

    kept: list[dict] = []
    excluded: dict[str, int] = {}

    def bump(reason: str):
        excluded[reason] = excluded.get(reason, 0) + 1

    for row in rows:
        # A row must AFFIRMATIVELY be classified forward-paper. An absent
        # stamp is not evidence of provenance, it is absence of it: every
        # genuine forward-paper row is stamped at write time
        # (prospective.run_step) and every legacy row is stamped by
        # classify_legacy_row, so `None` here means "never classified".
        # Admitting unclassified rows into a "verified-only" calibration
        # made the gate decorative — fixture and unstamped rows alike
        # sailed through simply for lacking the field.
        if row.get("evidenceClass") != EVIDENCE_FORWARD_PAPER:
            bump(EXCL_FIXTURE_TEST if row.get("evidenceClass") == EVIDENCE_FIXTURE else "other_class")
            continue
        if row.get("freezeId") not in (None, freeze_id):
            bump(EXCL_WRONG_FREEZE)
            continue
        if expected_commit and row.get("frozenGitCommit") not in (None, "", expected_commit):
            bump(EXCL_WRONG_FREEZE)
            continue
        miss = missing_problems(row)
        if miss:
            bump(EXCL_MISSING_DATA)
            continue
        num = numeric_problems(row)
        if num:
            bump(EXCL_INVALID_NUMERIC)
            continue
        temp = temporal_problems(row, now)
        if temp:
            bump(EXCL_BAD_TIMESTAMPS)
            continue
        if float(row.get("turnover", 0)) <= 1e-9:
            continue  # non-turnover rows carry no friction information
        kept.append(row)

    return kept, excluded


def new_observation_meta(
    *,
    freeze_manifest: dict,
    run_id: str,
    source: str = "forward-runner",
    evidence_class: str = EVIDENCE_FORWARD_PAPER,
    simulated_execution_at: str | None = None,
) -> dict:
    """Provenance block stamped onto every new cost observation."""
    meta = {
        "evidenceClass": evidence_class,
        "freezeId": f"freeze/{freeze_manifest['frozen_at_date']}",
        "frozenGitCommit": freeze_manifest.get("git_commit_at_freeze"),
        "codeFingerprint": freeze_manifest.get("code_sha256"),
        "runId": run_id,
        "source": source,
    }
    if simulated_execution_at is not None:
        meta["simulatedExecutionAt"] = simulated_execution_at
    return meta
